### ISSUE TITLE
closedoc()

### ISSUE THREAD

**Issue by buhtz** [pyexcel/pyexcel-ezodf#7]
There is no `closedoc()`.

How shoudl I handle `opendoc()` in that case? I want to close a file to be secure that I don't damage it.

**Comment by chfw** [comment]
I dont think you need closedoc(). The close action was embedded in [save()](https://github.com/pyexcel/pyexcel-ezodf/blob/master/ezodf/filemanager.py#L78)

I have [test case](https://github.com/pyexcel/pyexcel-ods3/blob/master/tests/test_bug_fixes.py#L102) to verify that specifically during reading, there is no open file handles.

That's all I know so far. Have you gotten damaged files?
