### ISSUE TITLE
Missing file CONTRIBUTORS.rst on tar.gz from pypi

### ISSUE THREAD

**Issue by williamjamir** [pyexcel/pyexcel-ezodf#9]
Hi,

I'm writing to let you know that the .tar.gz with the release 0.3.3 are missing a CONTRIBUTORS.rst file on [pypi](https://pypi.org/project/pyexcel-ezodf/#files), but the release 0.3.3 on [GitHub release](https://github.com/pyexcel/pyexcel-ezodf/releases) is present.

I think that this issue is worth checking, maybe it could be missing configuration on some file

**Comment by chfw** [comment]
Will put CONTRIBUTORS.rst in MANIFEST.in.
